### ISSUE TITLE
Consider building Layout elements instead of content parts

### ISSUE THREAD

**Issue by Piedone** [VirtoCommerce/vc-orchard-cms#5]
The content parts (and their drivers, etc.) all seem to be containers to display data coming from an API. However as of Orchard 1.9 the best way of "putting something dynamic on a page" is, apart from widgets, Layouts (the built-in Page content type uses that as well).

It seems to me that in this use-case it would be better to build Layout elements instead of content parts (though you can display a content item in a Layout too). E.g. by having a ProductList element (BTW I'd name them more Virto-specific, i.e. VirtoProductList) you could build a page (with Layouts) where you put the product list element onto the page (and you can put it into a grid, add text above it, etc.) and thus make the resulting layout drive your product list pages.

**Comment by Andrew-Orlov** [comment]
Well, ok. At first I thought only in widgets-way. I'll take a look on layouts.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
